USE admin_db;

-- Add missing columns to parents table
ALTER TABLE parents
ADD COLUMN wife_name VARCHAR(255),
ADD COLUMN mobile VARCHAR(20),
ADD COLUMN email VARCHAR(255),
ADD COLUMN occupation VARCHAR(255),
ADD COLUMN door_no VARCHAR(255),
ADD COLUMN street VARCHAR(255),
ADD COLUMN district VARCHAR(255),
ADD COLUMN state VARCHAR(255),
ADD COLUMN pincode VARCHAR(10),
ADD COLUMN husband_photo VARCHAR(255),
ADD COLUMN wife_photo VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Add missing columns to children table
ALTER TABLE children
ADD COLUMN photo VARCHAR(255),
ADD COLUMN created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP;
